spring:
  application:
    name: inditex
  datasource:
    url: jdbc:h2:mem:inditexdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      format-sql: true
  h2:
    console:
      enabled: true